# Generated by Django 3.1.4 on 2020-12-25 13:03

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.ImageField(blank=True, null=True, upload_to=files.models.upload_path)),
            ],
        ),
    ]
